<a href="https://colab.research.google.com/github/arnav39/d2el-en/blob/main/9_4_Recurrent_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 9.4 : Recurrent Neural Network

In [ ]:
!pip install matplotlib_inline
!pip install --upgrade d2l==1.0.0a0

In [2]:
import torch
from d2l import torch as d2l

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [3]:
X = torch.randn(3, 1)
W_xh = torch.randn(1, 4)
H = torch.randn(3, 4)
W_hh = torch.randn(4, 4)

output = torch.mm(X, W_xh) + torch.mm(H, W_hh) 
print(output.shape)

torch.Size([3, 4])


In [5]:
X_cat = torch.cat([X, H], dim=1)
W_cat = torch.cat([W_xh, W_hh], dim=0)

print(X_cat.shape)
print(W_cat.shape)

torch.Size([3, 5])
torch.Size([5, 4])


In [6]:
output_2 = torch.mm(X_cat, W_cat)
print(output_2.shape)
print(sum(output_2 == output))

torch.Size([3, 4])
tensor([2, 0, 1, 1])


In [9]:
print(output)

tensor([[ 2.2389, -0.5993, -0.8848, -0.5440],
        [ 1.7007, -0.1637,  0.1962, -0.3221],
        [ 3.0469, -0.8332, -1.3527, -1.2876]])


In [8]:
print(output_2)

tensor([[ 2.2389, -0.5993, -0.8848, -0.5440],
        [ 1.7007, -0.1637,  0.1962, -0.3221],
        [ 3.0469, -0.8332, -1.3527, -1.2876]])
