<a href="https://colab.research.google.com/github/arnav39/d2el-en/blob/main/2_1_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [99]:
a = np.array(["hi"])

In [100]:
a

array(['hi'], dtype='<U2')

In [5]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
X.shape

torch.Size([3, 4])

In [9]:
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
x.reshape(3, -1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
torch.zeros((1, 2, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
torch.randn??

In [20]:
torch.randn(4, 5)

tensor([[ 0.1649,  0.4184, -0.5085,  1.0088, -1.2907],
        [ 1.8641,  2.2460,  0.9466,  0.2463,  0.9883],
        [-0.0653,  0.6342, -0.6737, -1.8652,  0.7566],
        [ 1.3500, -0.4334, -0.2790,  2.3474,  0.1083]])

In [21]:
torch.tensor([[2, 1, 4, 4], [1, 2, 3, 4], [9, 8, 7, 6]])

tensor([[2, 1, 4, 4],
        [1, 2, 3, 4],
        [9, 8, 7, 6]])

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [24]:
X[-2]

tensor([4., 5., 6., 7.])

In [25]:
X[0:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[1:2]

tensor([[4., 5., 6., 7.]])

In [27]:
X[1]

tensor([4., 5., 6., 7.])

In [28]:
X[0:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [29]:
X[0, 3] = 98

In [30]:
X[0]

tensor([ 0.,  1.,  2., 98.])

In [31]:
X[:2, :] = 4
X

tensor([[ 4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.],
        [ 8.,  9., 10., 11.]])

In [32]:
torch.exp(X)

tensor([[5.4598e+01, 5.4598e+01, 5.4598e+01, 5.4598e+01],
        [5.4598e+01, 5.4598e+01, 5.4598e+01, 5.4598e+01],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [33]:
3 ** 4

81

In [34]:
X ** 2

tensor([[ 16.,  16.,  16.,  16.],
        [ 16.,  16.,  16.,  16.],
        [ 64.,  81., 100., 121.]])

In [35]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [40]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [39]:
x ** y

tensor([ 1,  4, 16, 64])

In [38]:
x * y

tensor([ 2,  4,  8, 16])

In [37]:
x - y

tensor([-1,  0,  2,  6])

In [36]:
x + y

tensor([ 3,  4,  6, 10])

In [59]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [42]:
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]), tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [45]:
torch.concat((X, Y), dim = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [46]:
torch.cat((X, Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [47]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [48]:
X != Y

tensor([[ True, False,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [50]:
(X == Y) + 0

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [51]:
X.sum()

tensor(66.)

In [53]:
X.mean().shape

torch.Size([])

In [54]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

In [55]:
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [56]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [57]:
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]), tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [61]:
before = id(Y)
Y = X+Y
after = id(Y)

print(after-before == 0, after-before)

False 89728


In [62]:
Z = torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
print("Id(Z) : ", id(Z))
Z[:] = X + Y
print("ID(Z) : ", id(Z))

Id(Z) :  139648639783664
ID(Z) :  139648639783664


In [64]:
bef = id(X)
X[:] += Y
after = id(X)
after == bef

True

In [65]:
bef = id(X)
X += Y
aft = id(X)
aft == bef

True

In [66]:
X

tensor([[ 4.,  7., 18., 21.],
        [22., 29., 36., 43.],
        [48., 51., 54., 57.]])

In [67]:
torch.from_numpy??

In [70]:
A = X.numpy()
B = torch.from_numpy(A)
print(A == B, "\n",type(A), "\n",type(B))

False 
 <class 'numpy.ndarray'> 
 <class 'torch.Tensor'>


In [71]:
A, B

(array([[ 4.,  7., 18., 21.],
        [22., 29., 36., 43.],
        [48., 51., 54., 57.]], dtype=float32), tensor([[ 4.,  7., 18., 21.],
         [22., 29., 36., 43.],
         [48., 51., 54., 57.]]))

In [73]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [74]:
X, Y

(tensor([[ 4.,  7., 18., 21.],
         [22., 29., 36., 43.],
         [48., 51., 54., 57.]]), tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]))

In [75]:
X > Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [76]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [77]:
X < Y + 0

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [79]:
torch.arange??

In [80]:
a1 = torch.arange(18).reshape(3, 2, 3)
a2 = torch.arange(start=-6, end=0).reshape(2, 3)

In [81]:
a1, a2

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]],
 
         [[12, 13, 14],
          [15, 16, 17]]]), tensor([[-6, -5, -4],
         [-3, -2, -1]]))

In [82]:
a1 + a2

tensor([[[-6, -4, -2],
         [ 0,  2,  4]],

        [[ 0,  2,  4],
         [ 6,  8, 10]],

        [[ 6,  8, 10],
         [12, 14, 16]]])

## Making a csv file in python

In [83]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')

with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [84]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [85]:
data.shape

(4, 3)

In [86]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]

In [88]:
inputs

NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN

In [89]:
targets

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

In [90]:
inputs = pd.get_dummies(inputs, dummy_na = True)
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1

In [91]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1

In [92]:
inputs.values

array([[3., 0., 1.],
       [2., 0., 1.],
       [4., 1., 0.],
       [3., 0., 1.]])

In [94]:
targets.values

array([127500, 106000, 178100, 140000])

## Now load the numpy objects into tensor

In [96]:
X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## Ex 2.2

## Q1:


*   The data frame has no null entries
*   All the column contain numerical data
*   The 0th column contains categorical data: M, F, I




In [102]:
file = open("abalone.data", "r")

In [ ]:
file.read()

In [132]:
pd.read_csv??

In [137]:
names = pd.read_csv("abalone.names", sep="\n\n\t")

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


In [138]:
names

1. Title of Database: Abalone data
0                                          2. Sources:
1                     (a) Original owners of database:
2                            Marine Resources Division
3               Marine Research Laboratories - Taroona
4    Department of Primary Industry and Fisheries, ...
..                                                 ...
107                                              26\t1
108                                              27\t2
109                                              29\t1
110                                        -----\t----
111                                        Total\t4177

[112 rows x 1 columns]

In [131]:
file = open("abalone.names", "rb")
file.read()

b'1. Title of Database: Abalone data\n\n2. Sources:\n\n   (a) Original owners of database:\n\tMarine Resources Division\n\tMarine Research Laboratories - Taroona\n\tDepartment of Primary Industry and Fisheries, Tasmania\n\tGPO Box 619F, Hobart, Tasmania 7001, Australia\n\t(contact: Warwick Nash +61 02 277277, wnash@dpi.tas.gov.au)\n\n   (b) Donor of database:\n\tSam Waugh (Sam.Waugh@cs.utas.edu.au)\n\tDepartment of Computer Science, University of Tasmania\n\tGPO Box 252C, Hobart, Tasmania 7001, Australia\n\n   (c) Date received: December 1995\n\n\n3. Past Usage:\n\n   Sam Waugh (1995) "Extending and benchmarking Cascade-Correlation", PhD\n   thesis, Computer Science Department, University of Tasmania.\n\n   -- Test set performance (final 1044 examples, first 3133 used for training):\n\t24.86% Cascade-Correlation (no hidden nodes)\n\t26.25% Cascade-Correlation (5 hidden nodes)\n\t21.5%  C4.5\n\t 0.0%  Linear Discriminate Analysis\n\t 3.57% k=5 Nearest Neighbour\n      (Problem encoded a

In [115]:
names = pd.read_csv("abalone.names", sep="\n")

In [120]:
names.iloc[4, :]

1. Title of Database: Abalone data    \tDepartment of Primary Industry and Fisheries...
Name: 4, dtype: object

In [7]:
column_names = ["sex", "length", "diameter", "height", "whole-weight", 
                "shucked-weight", "viscera-weight", "shell-weight", "rings"]
data = pd.read_csv("abalone.data", sep = ",", header=None, names=column_names)
data.head()

sex  length  diameter  height  whole-weight  shucked-weight  viscera-weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   shell-weight  rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [130]:
data.iloc[:, 0].unique()

array(['M', 'F', 'I'], dtype=object)

In [ ]:
data.nunique()

In [8]:
data.describe()

length     diameter       height  whole-weight  shucked-weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       viscera-weight  shell-weight        rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [ ]:
data.info()

In [ ]:
data.isna().sum()

In [ ]:
data.value_counts()

In [17]:
display(data)

sex  length  diameter  height  whole-weight  shucked-weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      viscera-weight  shell-weight  rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [9]:
data

sex  length  diameter  height  whole-weight  shucked-weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      viscera-weight  shell-weight  rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [ ]:
data.loc[0:5]

In [ ]:
data.loc[[1, 2, 3]]

In [ ]:
data.iloc[[1, 2, 3]]

In [30]:
data.iloc[1:3, 2:5]

diameter  height  whole-weight
1     0.265   0.090        0.2255
2     0.420   0.135        0.6770

In [ ]:
data.iloc[0:6]

In [ ]:
data.loc[data.height >= 0.1]

In [ ]:
data.loc[data.sex == "I"]

In [ ]:
data.loc[(data.sex == "I") & (data.height >= 0.1) & (data.diameter >= 0.09)]

In [ ]:
data.loc[data.sex == 'M']

In [ ]:
data[['diameter', 'height']]

In [ ]:
data.length

In [ ]:
data['shell-weight']

## 2.3 Linear Algebra

In [59]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

In [60]:
x.shape

torch.Size([])

In [33]:
x + y

tensor(5.)

In [34]:
x ** y

tensor(9.)

In [35]:
x/y

tensor(1.5000)

In [36]:
x = torch.arange(3)

In [38]:
len(x)

3

In [39]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [40]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
A == A.T

In [44]:
A = torch.arange(6, dtype=torch.float32).reshape(3, 2)
B = A.clone()

In [45]:
id(B) == id(A)

False

In [46]:
A, A+B

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.]]), tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]))

In [47]:
A * B

tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])

In [48]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)

In [49]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [50]:
X + a, X ** a

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), tensor([[[  0,   1,   4,   9],
          [ 16,  25,  36,  49],
          [ 64,  81, 100, 121]],
 
         [[144, 169, 196, 225],
          [256, 289, 324, 361],
          [400, 441, 484, 529]]]))

In [51]:
(a+X).shape

torch.Size([2, 3, 4])

In [55]:
x = torch.arange(3, dtype=torch.float32)
type(x[0])

torch.Tensor

In [56]:
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [57]:
A

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [58]:
A.shape, A.sum(), (A.sum()).shape

(torch.Size([3, 2]), tensor(15.), torch.Size([]))

In [62]:
A.shape, A.sum(axis=0), A.sum(axis=0).shape

(torch.Size([3, 2]), tensor([6., 9.]), torch.Size([2]))

In [63]:
A.shape, A.sum(axis=1), A.sum(axis=1).shape

(torch.Size([3, 2]), tensor([1., 5., 9.]), torch.Size([3]))

In [64]:
A.sum(axis=[0, 1])

tensor(15.)

In [65]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [66]:
A.mean(), A.sum(), A.numel()

(tensor(2.5000), tensor(15.), 6)

In [67]:
A.mean() == A.sum() / A.numel()

tensor(True)

In [68]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([2., 3.]), tensor([2., 3.]))

In [70]:
A.mean(axis=1), A.sum(axis=1) / A.shape[1], A.mean(axis=1) == A.sum(axis=1) / A.shape[1]

(tensor([0.5000, 2.5000, 4.5000]),
 tensor([0.5000, 2.5000, 4.5000]),
 tensor([True, True, True]))

In [71]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[1.],
        [5.],
        [9.]])

In [73]:
A.sum(axis=0, keepdim=True)

tensor([[6., 9.]])

In [74]:
A / sum_A

tensor([[0.0000, 1.0000],
        [0.4000, 0.6000],
        [0.4444, 0.5556]])

In [76]:
A

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [75]:
A.cumsum(axis=0)

tensor([[0., 1.],
        [2., 4.],
        [6., 9.]])

In [77]:
torch.ones??

In [78]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3)

print(x)
print(y)

tensor([0., 1., 2.])
tensor([1., 1., 1.])


In [79]:
torch.dot(x, y)

tensor(3.)

In [82]:
torch.sum(x * y)

tensor(3.)

In [83]:
torch.dot(x, y) == torch.sum(x * y)

tensor(True)

In [88]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
x = torch.arange(3, dtype=torch.float32)

A.shape, x.shape

(torch.Size([2, 3]), torch.Size([3]))

In [90]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]), tensor([0., 1., 2.]))

In [94]:
torch.mv??

In [89]:
torch.mv(A, x)

tensor([ 5., 14.])

In [92]:
A@x

tensor([ 5., 14.])

In [93]:
A@x == torch.mv(A, x)

tensor([True, True])

In [95]:
B = torch.arange(6).reshape(2, 3)
y = torch.arange(3)

torch.mv(B, y)

tensor([ 5, 14])

In [97]:
torch.mm??

In [96]:
A = torch.arange(6, dtype=torch.float).reshape(2, 3)
B = torch.ones(3, 4)

torch.mm(A, B)

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

In [98]:
A@B

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

In [ ]:
B@A

In [100]:
torch.mm(B, A)

RuntimeError: ignored

In [101]:
u = torch.tensor([3., -4.])
u

tensor([ 3., -4.])

In [102]:
torch.norm??

In [104]:
torch.norm(u)

tensor(5.)

In [105]:
torch.abs(u).sum()

tensor(7.)

In [106]:
## Frobenium norm
torch.norm(torch.ones(4, 9))

tensor(6.)

## Ex 2.3

### Q1:


In [107]:
A = torch.randn(4, 5)
A

tensor([[ 1.8376,  0.1329, -1.4867,  1.4723,  1.1444],
        [ 0.1498,  2.0732,  0.1362, -1.0467, -0.1799],
        [ 3.4771,  1.2181, -1.6180,  0.0088, -0.5268],
        [ 0.0493,  0.9274,  0.1636, -0.5918,  0.1712]])

In [114]:
(A.T.T == A).sum() / A.numel()

tensor(1.)

## Q2:

In [115]:
A = torch.randn(90, 90)
B = torch.randn(90, 90)

In [116]:
((A+B).T == A.T + B.T).sum() / A.numel()

tensor(1.)

## Q3:

In [117]:
((A+A.T).T == A + A.T).sum() / A.numel()

tensor(1.)

## Q4: len is returning the number of elements along the 0th axis

In [118]:
a = torch.arange(7)
len(a)

7

In [119]:
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

In [120]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [121]:
X = torch.randn(5, 6, 90)
len(X)

5

In [125]:
Y = torch.randn(100, 400)
len(Y)

100

In [129]:
c = torch.tensor(3.0)
c.shape, len(c)

TypeError: ignored

## Q5: 

* len(X) corresponds to the length of the 0th axis of X
  for scalar tensors it gives an error

## Q6:

In [131]:
A = torch.arange(6, dtype=torch.float32).reshape(3, 2)
A

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [132]:
A.sum(axis=1)

tensor([1., 5., 9.])

In [133]:
A / A.sum(axis=1)

RuntimeError: ignored

In [134]:
A / A.sum(axis=1, keepdim=True)

tensor([[0.0000, 1.0000],
        [0.4000, 0.6000],
        [0.4444, 0.5556]])

## Q7: 

l2 norm between 2 coordinates

## Q8:

In [135]:
x = torch.ones(2, 3, 4)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [136]:
x.shape

torch.Size([2, 3, 4])

In [137]:
x.sum(axis=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [138]:
x.sum(axis=1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [139]:
x.sum(axis=2)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

## Q9:

In [143]:
x = torch.arange(40, dtype=torch.float32).reshape(4, 2, 5)
x

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]],

        [[30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]]])

In [144]:
np.linalg.norm(x)

143.31783

In [145]:
torch.norm(x)

tensor(143.3178)

## Q10:

multipying A and B first gives us comparitively smaller matrices to work with
as compared to when we first mulitply B and C

In [146]:
A = torch.randn(2**10, 2**16)
B = torch.randn(2**16, 2**5)
C = torch.randn(2**5, 2**14)

In [147]:
torch.mm(A, torch.mm(B, C))

tensor([[  405.4131,   800.9255,  1139.9124,  ...,  1992.9435, -1139.9321,
          1326.7667],
        [ 1819.2869,  -449.3789,  -871.2088,  ...,  -490.5907,  1973.8264,
          -291.3063],
        [  761.1656,  -670.1636, -3143.5095,  ...,  4258.8301, -2353.0842,
         -4688.3599],
        ...,
        [ 1461.9907,  3669.5374,   855.3022,  ...,   283.5349, -1823.9968,
         -1662.1705],
        [ 2040.4781, -1303.5697,  1640.0363,  ..., -1619.3749,   996.1019,
          1261.9495],
        [-1912.0277, -1483.3771, -3663.0972,  ..., -1088.3455, -1175.9589,
         -1666.7401]])

In [148]:
torch.mm(torch.mm(A, B), C)

tensor([[  405.4123,   800.9250,  1139.9125,  ...,  1992.9440, -1139.9324,
          1326.7671],
        [ 1819.2881,  -449.3799,  -871.2082,  ...,  -490.5923,  1973.8280,
          -291.3072],
        [  761.1649,  -670.1633, -3143.5083,  ...,  4258.8281, -2353.0845,
         -4688.3564],
        ...,
        [ 1461.9918,  3669.5383,   855.3030,  ...,   283.5352, -1823.9962,
         -1662.1693],
        [ 2040.4773, -1303.5712,  1640.0363,  ..., -1619.3751,   996.1018,
          1261.9481],
        [-1912.0276, -1483.3773, -3663.0967,  ..., -1088.3467, -1175.9594,
         -1666.7429]])

## Q11:

AB takes less time to compute rather than AC^T. I think some of the time is taken by the transpose function, but when we set C = B.T then the time taken in both the cases is almost same, that i don't know why??

In [152]:
import time

In [149]:
A = torch.randn(2**10, 2**16)
B = torch.randn(2**16, 2**5)
C = torch.randn(2**5, 2**16)

In [153]:
start = time.time()
torch.mm(A, B)
end = time.time()
print(end - start)

0.11486959457397461


In [154]:
start = time.time()
torch.mm(A, C.T)
end = time.time()
print(end - start)

0.18561100959777832


In [157]:
C = B.T.clone()
start = time.time()
torch.mm(A, C.T)
end = time.time()
print(end - start)

0.12226629257202148


## Q12: stack function

In [164]:
torch.stack??

In [160]:
x = torch.tensor([[1., 3., 6.], [10., 13., 20.]])
y = torch.tensor([[2., 7., 9.], [14., 21., 34.]])

print("Tensor x:\n", x)
print("Tensor y:\n", y)

Tensor x:
 tensor([[ 1.,  3.,  6.],
        [10., 13., 20.]])
Tensor y:
 tensor([[ 2.,  7.,  9.],
        [14., 21., 34.]])


In [167]:
print("join tensors in dimension 2:\n"), torch.stack((x, y), dim=2)

join tensors in dimension 2:



(None, tensor([[[ 1.,  2.],
          [ 3.,  7.],
          [ 6.,  9.]],
 
         [[10., 14.],
          [13., 21.],
          [20., 34.]]]))

In [166]:
print("join tensors in dimension 1:\n", torch.stack((x, y), dim=1))

join tensors in dimension 1:
 tensor([[[ 1.,  3.,  6.],
         [ 2.,  7.,  9.]],

        [[10., 13., 20.],
         [14., 21., 34.]]])


In [165]:
print("join tensors in dimension 0:\n", torch.stack((x, y), dim=0))

join tensors in dimension 0:
 tensor([[[ 1.,  3.,  6.],
         [10., 13., 20.]],

        [[ 2.,  7.,  9.],
         [14., 21., 34.]]])


In [163]:
print("join tensors\n", torch.stack((x, y)))

join tensors
 tensor([[[ 1.,  3.,  6.],
         [10., 13., 20.]],

        [[ 2.,  7.,  9.],
         [14., 21., 34.]]])


In [158]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)

In [159]:
A.shape

torch.Size([100, 200])

In [168]:
t = torch.stack((A, B, C), dim=0)

In [169]:
t.shape
## dimensionality = 3

torch.Size([3, 100, 200])

In [172]:
(t[1, :, :] == B).sum() / B.numel()

tensor(1.)

In [174]:
(t[1] == B).sum()

tensor(20000)

In [175]:
(t[1] == A).sum()

tensor(0)

In [176]:
(t[2] == C).sum()

tensor(20000)

In [177]:
(t[4] == B).sum()

IndexError: ignored

In [178]:
(t[1] == A).sum()

tensor(0)