<a href="https://colab.research.google.com/github/arnav39/d2el-en/blob/main/Chapter-6(Builder's%20Guide)/6_2_6_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6.2 : Parameter Management

In [ ]:
import torch
from torch import nn

In [ ]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.randn(2, 4)
net(X).shape

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

In [ ]:
net

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
net[0].state_dict()

OrderedDict([('weight', tensor([[ 0.4381, -0.2563, -0.1464,  0.4440],
                      [ 0.3292, -0.0811,  0.4635,  0.4075],
                      [ 0.2028, -0.0660,  0.3773,  0.3556],
                      [ 0.1367,  0.3034,  0.4320, -0.3711],
                      [ 0.4030, -0.1065,  0.4554, -0.3622],
                      [-0.4225, -0.0315,  0.2933, -0.4113],
                      [ 0.0942,  0.3222,  0.2352, -0.0955],
                      [ 0.4266, -0.1662, -0.3624, -0.3383]])),
             ('bias',
              tensor([ 0.4015,  0.3032,  0.0953, -0.3081,  0.3012, -0.0086, -0.1487,  0.0759]))])

In [ ]:
net[1]

ReLU()

In [ ]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[-0.0523,  0.0394,  0.0570, -0.3464,  0.0556,  0.0242, -0.3192, -0.2391]])),
             ('bias', tensor([-0.3147]))])

In [ ]:
type(net[2].bias), type(net[2].weight)

(torch.nn.parameter.Parameter, torch.nn.parameter.Parameter)

In [ ]:
net[2].bias.data

tensor([-0.3147])

In [ ]:
net[2].weight.data.T

tensor([[-0.0523],
        [ 0.0394],
        [ 0.0570],
        [-0.3464],
        [ 0.0556],
        [ 0.0242],
        [-0.3192],
        [-0.2391]])

In [ ]:
net[2].weight.grad == None

True

In [ ]:
# accessing all the parameters : 
[(name, param) for name, param in net.named_parameters()]

[('0.weight', Parameter containing:
  tensor([[ 0.4381, -0.2563, -0.1464,  0.4440],
          [ 0.3292, -0.0811,  0.4635,  0.4075],
          [ 0.2028, -0.0660,  0.3773,  0.3556],
          [ 0.1367,  0.3034,  0.4320, -0.3711],
          [ 0.4030, -0.1065,  0.4554, -0.3622],
          [-0.4225, -0.0315,  0.2933, -0.4113],
          [ 0.0942,  0.3222,  0.2352, -0.0955],
          [ 0.4266, -0.1662, -0.3624, -0.3383]], requires_grad=True)),
 ('0.bias', Parameter containing:
  tensor([ 0.4015,  0.3032,  0.0953, -0.3081,  0.3012, -0.0086, -0.1487,  0.0759],
         requires_grad=True)),
 ('2.weight', Parameter containing:
  tensor([[-0.0523,  0.0394,  0.0570, -0.3464,  0.0556,  0.0242, -0.3192, -0.2391]],
         requires_grad=True)),
 ('2.bias', Parameter containing:
  tensor([-0.3147], requires_grad=True))]

In [ ]:
# tied Parameters

In [ ]:
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.LazyLinear(1))

net(X)

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor([[-0.1048],
        [-0.1122]], grad_fn=<AddmmBackward0>)

In [ ]:
net[2].weight.data == net[4].weight.data

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])

In [ ]:
net[2].weight.data[0, 0] = 100
net[2].weight.data

tensor([[ 1.0000e+02,  1.5629e-01,  1.7371e-01,  1.7948e-01, -1.9413e-01,
         -1.3633e-02,  2.3916e-01,  1.8275e-01],
        [ 5.8688e-02, -1.6743e-01, -3.2194e-01, -8.2838e-02, -3.3113e-01,
          5.2319e-02,  2.3076e-01, -3.1964e-02],
        [ 9.7246e-02,  1.8917e-02, -1.7082e-02,  2.7821e-01,  4.8336e-02,
          3.2752e-01, -2.2913e-01, -2.1909e-01],
        [-2.6832e-01, -1.2131e-01,  6.6699e-03,  1.1712e-01, -2.3786e-01,
         -3.0982e-01,  2.2601e-01, -8.9856e-02],
        [ 3.1830e-01,  3.0981e-01, -1.6538e-01, -8.9604e-02, -2.7544e-01,
          1.1462e-01, -1.6542e-01, -1.8158e-01],
        [ 2.3907e-01, -2.1194e-03, -4.5691e-02, -2.1805e-01,  1.0747e-01,
          2.1401e-02, -1.9279e-01, -2.5022e-01],
        [ 2.0308e-01,  9.6534e-03, -2.0628e-01,  2.6295e-01,  1.9924e-01,
          7.6789e-03,  7.1431e-02,  1.8370e-01],
        [ 1.8169e-01,  1.3398e-02,  1.8428e-02,  2.3559e-01, -1.1444e-01,
         -1.1785e-02, -8.2226e-02,  8.4677e-02]])

In [ ]:
print(net[2].weight.data[0] == net[4].weight.data[0]) # thus the wights of the 2nd and 3rd layer are connected

tensor([True, True, True, True, True, True, True, True])


## Ex 6.2

### Q1:

In [ ]:
class NestMLP(nn.Module):

  def __init__(self):
    super().__init__()
    self.net = nn.Sequential(nn.LazyLinear(64), nn.ReLU(),
                             nn.LazyLinear(32), nn.ReLU())
    self.linear = nn.LazyLinear(16)

  def forward(self, X):
    return self.linear(self.net(X))

In [ ]:
net = NestMLP()
X = torch.randn(2, 10)
net(X).shape

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 16])

In [ ]:
  net.net[0].bias.data.shape, net.net[0].weight.data.shape

(torch.Size([64]), torch.Size([64, 10]))

In [ ]:
[(name, param) for name, param in net.net.named_parameters()]

In [ ]:
net.linear.bias.data, net.linear.weight.data

### Q2:

In [ ]:
class MLP(nn.Module):

  def __init__(self):
    super().__init__()
    shared = nn.LazyLinear(2)
    self.net = nn.Sequential(nn.LazyLinear(2), nn.ReLU(),
                             shared, nn.ReLU(),
                             shared, nn.ReLU(),
                             nn.LazyLinear(1))
    self.lr = 0.01
    
  def forward(self, X):
    return self.net(X)

In [ ]:
# data : 
X = torch.randn(1000, 1)
y = torch.randn(1000, 1)

In [ ]:
model = MLP()
optimizer = torch.optim.SGD(model.parameters(), model.lr)
crit = nn.MSELoss()

In [ ]:
max_epochs = 2

for epoch in range(max_epochs):

  # forward pass : y_hat and loss
  y_hat = model(X)
  loss = crit(y_hat, y)

  # backward pass : gradient
  loss.backward()

  # update the params 
  optimizer.step()

  # want to see the parameters and gradients and the end of each epoch for each layer
  print([(name, param, param.grad) for name, param in model.net.named_parameters()])

  # zero the grad
  optimizer.zero_grad()

  print(f"epoch : {epoch+1}/{max_epochs}, loss = {loss.item():.4f}")

[('0.weight', Parameter containing:
tensor([[-0.2698],
        [ 0.1232]], requires_grad=True), tensor([[-4.3865e-03],
        [ 5.5687e-06]])), ('0.bias', Parameter containing:
tensor([ 0.6958, -0.2922], requires_grad=True), tensor([2.3329e-02, 3.6950e-06])), ('2.weight', Parameter containing:
tensor([[0.2833, 0.4397],
        [0.1358, 0.0921]], requires_grad=True), tensor([[0.0416, 0.0298],
        [0.0636, 0.1738]])), ('2.bias', Parameter containing:
tensor([-0.1647,  0.3205], requires_grad=True), tensor([0.1192, 0.4894])), ('6.weight', Parameter containing:
tensor([[0.0951, 0.5130]], requires_grad=True), tensor([[0.0248, 0.3001]])), ('6.bias', Parameter containing:
tensor([0.2322], requires_grad=True), tensor([0.8119]))]
epoch : 1/2, loss = 1.1381
[('0.weight', Parameter containing:
tensor([[-0.2698],
        [ 0.1232]], requires_grad=True), tensor([[-4.3442e-03],
        [ 3.4269e-06]])), ('0.bias', Parameter containing:
tensor([ 0.6956, -0.2922], requires_grad=True), tensor([2.18

# 6.3 : Parameter Initialization

In [ ]:
import torch
from torch import nn

In [ ]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.randn(2, 4)
net(X)

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor([[-0.2939],
        [-0.0141]], grad_fn=<AddmmBackward0>)

In [ ]:
type(net[0]) == nn.Linear

True

In [ ]:
nn.init??

In [ ]:
net[0].weight

Parameter containing:
tensor([[-0.3658,  0.0247, -0.4847, -0.4327],
        [-0.3415, -0.0106, -0.4513, -0.0614],
        [-0.4063,  0.3049, -0.2068, -0.1867],
        [ 0.3966, -0.2243,  0.3046,  0.0192],
        [-0.3275, -0.3273,  0.2287, -0.0601],
        [-0.0366,  0.4873, -0.0008,  0.2754],
        [ 0.3241,  0.4014, -0.2576,  0.3616],
        [ 0.3505,  0.2367, -0.3790,  0.0182]], requires_grad=True)

In [ ]:
def init_normal(module):
  if type(module) == nn.Linear:
    nn.init.normal_(module.weight, mean=0.0, std=0.01)
    nn.init.zeros_(module.bias)

In [ ]:
net.apply(init_normal)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
net[0].weight.data[0]

tensor([-0.0023,  0.0037, -0.0031,  0.0035])

In [ ]:
net[0].weight.data.std(), net[0].weight.data.mean()

(tensor(0.0109), tensor(-0.0004))

In [ ]:
net[0].bias.data

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
def init_constant(module):
  if type(module) == nn.Linear:
    nn.init.constant_(module.weight, 1)
    nn.init.zeros_(module.bias)

In [ ]:
net.apply(init_constant)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
net[0].weight.data, net[0].bias.data

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), tensor([0., 0., 0., 0., 0., 0., 0., 0.]))

In [ ]:
# Xavier initialization

def init_xavier(module):
  if type(module) == nn.Linear:
    nn.init.xavier_uniform_(module.weight)

In [ ]:
def init_42(module):
  if type(module) == nn.Linear:
    nn.init.constant_(module.weight, 42)

In [ ]:
net[0]

Linear(in_features=4, out_features=8, bias=True)

In [ ]:
net[0].apply(init_xavier)
net[2].apply(init_42)

Linear(in_features=8, out_features=1, bias=True)

In [ ]:
print(net[0].weight.data[0])
print(net[0].weight.data.mean(), net[0].weight.data.std())

tensor([-0.5619, -0.2062,  0.6404, -0.3916])
tensor(0.0389) tensor(0.3548)


In [ ]:
a = nn.Linear(2, 1)

In [ ]:
print(*[(name, param.shape) for name, param in a.named_parameters()][0])

weight torch.Size([1, 2])


In [ ]:
nn.init.uniform_??

In [ ]:
# custom init

def my_init(module):
  if type(module) == nn.Linear:
    print("Init ", *[(name, param.shape) for name, param in module.named_parameters()][0])
    nn.init.uniform_(module.weight, -10, 10)
    module.weight.data *= module.weight.data.abs() >= 5

In [ ]:
net.apply(my_init)

Init  weight torch.Size([8, 4])
Init  weight torch.Size([1, 8])


Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
net[0].weight.data

tensor([[-5.9242, -0.0000,  0.0000, -0.0000],
        [-6.2601,  0.0000, -8.9792, -6.1125],
        [ 5.1667,  0.0000, -8.6108, -9.5067],
        [-5.3649, -0.0000, -0.0000,  0.0000],
        [ 0.0000, -0.0000, -0.0000, -0.0000],
        [ 6.0985,  0.0000, -0.0000, -0.0000],
        [ 0.0000, -0.0000,  0.0000,  0.0000],
        [-0.0000,  8.2776, -9.4722,  0.0000]])

In [ ]:
net[0].weight.data[:] += 1
net[0].weight.data

tensor([[-4.9242,  1.0000,  1.0000,  1.0000],
        [-5.2601,  1.0000, -7.9792, -5.1125],
        [ 6.1667,  1.0000, -7.6108, -8.5067],
        [-4.3649,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 7.0985,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  9.2776, -8.4722,  1.0000]])

In [ ]:
net[0].weight.data[0, 0] = 42
print(net[0].weight.data[0])

tensor([42.,  1.,  1.,  1.])


# 6.4 : Lazy Initialization

In [ ]:
!pip install matplotlib_inline
!pip install --upgrade d2l==1.0.0a0

In [ ]:
import torch 
from torch import nn
from d2l import torch as d2l

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [ ]:
net = nn.Sequential(nn.LazyLinear(256), nn.ReLU(), nn.LazyLinear(10))

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [ ]:
net[0].weight, net[0].bias

(<UninitializedParameter>, <UninitializedParameter>)

In [ ]:
net[2].weight, net[2].bias

(<UninitializedParameter>, <UninitializedParameter>)

In [ ]:
X = torch.randn(2, 20)
net(X)

tensor([[ 0.0496,  0.0038,  0.2014, -0.2408,  0.2404,  0.0910,  0.0797,  0.1881,
          0.3260, -0.0411],
        [ 0.0582, -0.2042,  0.1336,  0.3856,  0.0877,  0.0228,  0.0095,  0.2333,
          0.2788,  0.1618]], grad_fn=<AddmmBackward0>)

In [ ]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([256, 20])),
 ('0.bias', torch.Size([256])),
 ('2.weight', torch.Size([10, 256])),
 ('2.bias', torch.Size([10]))]

In [ ]:
@d2l.add_to_class(d2l.DataModule)
def apply_init(self, inputs, init=None):
  self.forward(inputs)
  if init is not None:
    self.net.apply(init)

## Ex 6.4:

### Q1: 
- we don't get immediate initialization

In [ ]:
net = nn.Sequential(nn.Linear(4, 2), nn.ReLU(), nn.LazyLinear(6), nn.ReLU(), nn.LazyLinear(1))

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [ ]:
net2 = nn.Sequential(nn.Linear(4, 2), nn.ReLU(), nn.LazyLinear(6), nn.ReLU(), nn.LazyLinear(1))
[(name, param.shape) for name, param in net2.named_parameters()]

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


RuntimeError: ignored

In [ ]:
[(name, param.shape) for name, param in net.named_parameters()]

RuntimeError: ignored

### Q2:

In [ ]:
net = nn.Sequential(nn.Linear(10, 20), nn.ReLU(), nn.Linear(30, 1))

In [ ]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([20, 10])),
 ('0.bias', torch.Size([20])),
 ('2.weight', torch.Size([1, 30])),
 ('2.bias', torch.Size([1]))]

In [ ]:
X = torch.randn(1, 10)
net(X)

RuntimeError: ignored

# 6.5 : Custom Layers

In [2]:
!pip install matplotlib_inline
!pip install --upgrade d2l==1.0.0a0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 92 kB 1.1 MB/s 
     |████████████████████████████████| 121 kB 65.8 MB/s 
     |████████████████████████████████| 1.6 MB 72.7 MB/s 
     |████████████████████████████████| 83 kB 2.7 MB/s 


In [ ]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [ ]:
class CenteredLayer(nn.Module):

  # custom layer without any parameters

  def __init__(self):
    super().__init__()

  def forward(self, X):
    return X - X.mean()

In [ ]:
layer = CenteredLayer()
x = torch.arange(5, dtype=torch.float32)
layer(x)

tensor([-2., -1.,  0.,  1.,  2.])

In [ ]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [ ]:
x = torch.arange(5, dtype=torch.float32)
net(x).mean()

tensor(2.6077e-08, grad_fn=<MeanBackward0>)

In [ ]:
torch.zeros(3,)

tensor([0., 0., 0.])

In [ ]:
# layers with parameters:

class MyLinear(nn.Module):
  
  def __init__(self, in_units, units):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units, units))
    self.bias = nn.Parameter(torch.zeros(units))

  def forward(self, X):
    linear = torch.mm(X, self.weight.data) + self.bias.data
    return F.relu(linear)

In [ ]:
linear = MyLinear(5, 3)
print(linear.weight, linear.bias)

Parameter containing:
tensor([[-1.4032,  1.6394,  0.5610],
        [-0.6801,  0.9381,  0.5027],
        [-1.3480,  1.7244,  0.6592],
        [ 1.2576,  0.0978, -0.9279],
        [ 0.3018,  0.5490,  3.2611]], requires_grad=True) Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [ ]:
linear(torch.randn(2, 5)) # forward prop

tensor([[4.1940, 0.0000, 0.0000],
        [0.0000, 6.9300, 5.2530]])

In [ ]:
net = nn.Sequential(nn.Linear(64, 8), nn.ReLU(), MyLinear(8, 1))
net(torch.randn(2, 64))

tensor([[0.6922],
        [0.8097]], grad_fn=<ReluBackward0>)

In [ ]:
net

Sequential(
  (0): Linear(in_features=64, out_features=8, bias=True)
  (1): ReLU()
  (2): MyLinear()
)

In [ ]:
net[2].weight.data

tensor([[ 0.3108],
        [-0.5707],
        [-0.6616],
        [-0.1237],
        [-1.1553],
        [-0.6196],
        [-0.1295],
        [ 3.0451]])

## Ex 6.5:

### Q1:

In [ ]:
a = torch.randn(5, 5)
torch.randn(a.shape)

tensor([[-1.0971,  1.1966,  0.7876, -0.3313,  0.2007],
        [ 0.9734, -2.2663,  0.7433, -1.4301,  0.3147],
        [-1.3858, -1.1057, -1.4039, -0.7757,  0.5048],
        [-0.2304,  1.7303,  0.5853,  1.1391,  0.4691],
        [ 0.5361, -1.1057,  0.6948,  0.8105, -2.3090]])

In [ ]:
class RedLayer(nn.Module):

  # we are performing x.T * W * x

  def __init__(self, num_inputs, num_outputs):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(num_inputs, num_outputs))
    self.bias = nn.Parameter(torch.randn(num_outputs))

  def forward(self, X):
   out = torch.mm(X, self.weight)
   out = torch.mm(out, X)
   return F.relu(X)

In [ ]:
layer = RedLayer(4, 1)
X = torch.randn(1, 4)
layer(X)

tensor([[0.1928, 0.9445, 0.0000, 0.9150]])

# 6.6 : File I/O

In [ ]:
import torch
from torch import nn
import torch.nn.functional as F

In [ ]:
x = torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


In [ ]:
torch.save??

In [ ]:
torch.save(x, 'x-file')

In [ ]:
torch.load??

In [ ]:
x2 = torch.load('x-file')

In [ ]:
print(x2)

tensor([0, 1, 2, 3])


In [ ]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')

In [100]:
x2, y2 = torch.load('x-files')

In [101]:
print(x2, y2)

tensor([0, 1, 2, 3]) tensor([0., 0., 0., 0.])


In [102]:
my_dict = {'x' : x, 'y' : y}
print(my_dict)

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


In [103]:
torch.save(my_dict, 'mydict')

In [104]:
mydict2 = torch.load('mydict')
print(mydict2)

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


In [105]:
class MLP(nn.Module):

  def __init__(self):
    super().__init__()
    self.hidden = nn.LazyLinear(256)
    self.output = nn.LazyLinear(10)

  def forward(self, x):
    return self.output(F.relu(self.hidden(X)))

In [106]:
net = MLP()
X = torch.randn(2, 20)
y = net(X)

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [108]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.0287, -0.0146,  0.0701,  ...,  0.1563,  0.0158, -0.0303],
                      [ 0.0798, -0.1728,  0.1105,  ..., -0.2046,  0.2036, -0.1254],
                      [ 0.1253, -0.1406, -0.0009,  ..., -0.0819, -0.0044,  0.2143],
                      ...,
                      [ 0.1281,  0.0398,  0.0074,  ...,  0.1229, -0.1714,  0.1434],
                      [ 0.1541, -0.0851,  0.0280,  ...,  0.0616,  0.0299, -0.2087],
                      [ 0.1846,  0.0469, -0.1249,  ...,  0.1342, -0.0126, -0.1100]])),
             ('hidden.bias',
              tensor([ 0.1265,  0.0047, -0.0804,  0.0236, -0.0020, -0.1066,  0.0773, -0.0313,
                       0.1432, -0.1947, -0.1669, -0.2203,  0.1170,  0.0254,  0.1359,  0.0636,
                       0.0987,  0.1478,  0.0551,  0.1652,  0.1703, -0.0137,  0.0888,  0.0736,
                      -0.0634,  0.0950,  0.0031,  0.0596, -0.1446,  0.0529,  0.1491, -0.0073,
                       0.2232,

In [109]:
torch.save(net.state_dict(), 'mlp.params')

In [110]:
clone = MLP()

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [111]:
clone.load_state_dict(torch.load('mlp.params'))

<All keys matched successfully>

In [112]:
clone.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.0287, -0.0146,  0.0701,  ...,  0.1563,  0.0158, -0.0303],
                      [ 0.0798, -0.1728,  0.1105,  ..., -0.2046,  0.2036, -0.1254],
                      [ 0.1253, -0.1406, -0.0009,  ..., -0.0819, -0.0044,  0.2143],
                      ...,
                      [ 0.1281,  0.0398,  0.0074,  ...,  0.1229, -0.1714,  0.1434],
                      [ 0.1541, -0.0851,  0.0280,  ...,  0.0616,  0.0299, -0.2087],
                      [ 0.1846,  0.0469, -0.1249,  ...,  0.1342, -0.0126, -0.1100]])),
             ('hidden.bias',
              tensor([ 0.1265,  0.0047, -0.0804,  0.0236, -0.0020, -0.1066,  0.0773, -0.0313,
                       0.1432, -0.1947, -0.1669, -0.2203,  0.1170,  0.0254,  0.1359,  0.0636,
                       0.0987,  0.1478,  0.0551,  0.1652,  0.1703, -0.0137,  0.0888,  0.0736,
                      -0.0634,  0.0950,  0.0031,  0.0596, -0.1446,  0.0529,  0.1491, -0.0073,
                       0.2232,

In [114]:
clone.eval??

In [115]:
clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [117]:
y_clone = clone(X)
(y_clone == y).sum() / y.numel()

tensor(1.)

In [118]:
net

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

## Ex 6.6 :

### Q2:

In [123]:
torch.save(net.hidden.state_dict(), "hidden-layer.params")

In [139]:
class MLPNew(nn.Module):

  def __init__(self):
    super().__init__()
    self.lin = nn.Linear(20, 256)

  def forward(self, X):
    return self.lin(X)

In [132]:
net = MLPNew()
net.lin.weight = nn.Parameter(clone.state_dict()['hidden.weight'])

In [133]:
net.lin.state_dict()

OrderedDict([('weight',
              tensor([[ 0.0287, -0.0146,  0.0701,  ...,  0.1563,  0.0158, -0.0303],
                      [ 0.0798, -0.1728,  0.1105,  ..., -0.2046,  0.2036, -0.1254],
                      [ 0.1253, -0.1406, -0.0009,  ..., -0.0819, -0.0044,  0.2143],
                      ...,
                      [ 0.1281,  0.0398,  0.0074,  ...,  0.1229, -0.1714,  0.1434],
                      [ 0.1541, -0.0851,  0.0280,  ...,  0.0616,  0.0299, -0.2087],
                      [ 0.1846,  0.0469, -0.1249,  ...,  0.1342, -0.0126, -0.1100]])),
             ('bias',
              tensor([ 0.0069, -0.2186, -0.1652,  0.0923,  0.0552,  0.0040,  0.0875,  0.1530,
                      -0.0502, -0.1344,  0.0320,  0.1739, -0.0271, -0.2046,  0.0388, -0.1067,
                       0.0258, -0.0936,  0.0227, -0.0755,  0.0630,  0.0881, -0.0777, -0.1336,
                      -0.1337, -0.0519,  0.0351, -0.0594,  0.0970,  0.1163, -0.0597,  0.1036,
                       0.1027, -0.2203, -0.0

### Q3:

In [134]:
torch.save(net, 'net')

In [140]:
net2 = torch.load('net')

In [141]:
net2

MLPNew(
  (lin): Linear(in_features=20, out_features=256, bias=True)
)

# 6.7 : GPUs

In [1]:
!nvidia-smi

Wed Dec 14 19:47:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0    29W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
from torch import nn
from d2l import torch as d2l

In [6]:
def cpu():
  return torch.device('cpu')

def gpu(i=0):
  return torch.device(f"cuda:{i}")

In [7]:
cpu(), gpu(), gpu(1)

(device(type='cpu'),
 device(type='cuda', index=0),
 device(type='cuda', index=1))

In [8]:
# number of available gpus
def num_gpus():
  return torch.cuda.device_count()

In [9]:
num_gpus()

1

In [10]:
def try_gpu(i=0):
  if num_gpus() >= i+1:
    return gpu(i)
  return cpu()

In [11]:
def try_all_gpus():
  return [gpu(i) for i in range(num_gpus())]

In [12]:
try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [13]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [14]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [15]:
X.cuda(0) is X

True

In [16]:
net = nn.Sequential(nn.LazyLinear(1))
net = net.to(device=try_gpu())

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [17]:
net

Sequential(
  (0): LazyLinear(in_features=0, out_features=1, bias=True)
)

In [19]:
X = torch.randn(4, 5).to(device=try_gpu())
net(X)

tensor([[ 0.0521],
        [-1.0764],
        [ 1.0121],
        [ 0.5752]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [21]:
net[0].weight.data

tensor([[ 0.0932,  0.3174, -0.1168, -0.3216, -0.3239]], device='cuda:0')

In [22]:
net[0].bias.data

tensor([0.0663], device='cuda:0')

In [23]:
@d2l.add_to_class(d2l.Trainer)
def __init__(self, max_epochs, num_gpus=0, gradient_clip_val=0):
  self.save_hyperparameters()
  self.gpus = [d2l.gpu(i) for i in range(min(num_gpus, d2l.num_gpus()))]

@d2l.add_to_class(d2l.Trainer)
def prepare_batch(self, batch):
  if self.gpus:
    batch = [a.to(self.gpus[0]) for a in batch]
  return batch

@d2l.add_to_class(d2l.Trainer)
def prepare_model(self, model):
  model.trainer = self
  model.board.xlim = [0, self.max_epochs]
  if self.gpus:
    model.to(self.gpus[0])
  self.model = model

## Ex 6.7:

### Q2:

In [ ]:
net.to(device=try_gpu())

### Q3:

In [39]:
X = torch.randn(100, 100).to(device=try_gpu())
for i in range(1000):
  X = torch.mm(X, torch.randn(100, 100).to(device=gpu()))


log_X_fn = torch.log(torch.sqrt(((X.reshape(-1)) ** 2).sum()))
ans = log_X_fn.to(device=cpu())
print(ans)

In [38]:
torch.rand??