<a href="https://colab.research.google.com/github/arnav39/d2el-en/blob/main/7_4-7_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 7.4 : Multiple Input and Multiple Output channels

In [ ]:
!pip install matplotlib_inline
!pip install --upgrade d2l==1.0.0a0

In [2]:
import torch
from d2l import torch as d2l

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [3]:
def corr2d(X, K):
  h, w = K.shape
  Y = torch.zeros(X.shape[0]-h+1, X.shape[1]-w+1)

  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i, j] = (X[i:i+h, j:j+w] * K).sum()
  return Y

In [4]:
X = torch.arange(1, 10, dtype=torch.float32).reshape(3, 3)
K = torch.arange(1, 5, dtype=torch.float32).reshape(2, 2)
print(X, K)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) tensor([[1., 2.],
        [3., 4.]])


In [5]:
corr2d(X, K)

tensor([[37., 47.],
        [67., 77.]])

In [6]:
def corr2d_multi_in(X, K):
  # iterate through the zero'th dimension of K first, then add them up
  return sum(corr2d(x, k) for x, k in zip(X, K))

In [7]:
torch.stack??

In [8]:
x1 = torch.arange(1, 10, dtype=torch.float32).reshape(3, 3)
x2 = torch.arange(0, 9, dtype=torch.float32).reshape(3, 3)
print(x1, '\n', x2)

X = torch.stack([x1, x2])
print(X.shape)

k1 = torch.arange(1, 5, dtype=torch.float32).reshape(2, 2)
k2 = torch.arange(0, 4, dtype=torch.float32).reshape(2, 2)
print(k1, '\n', k2)

K = torch.stack([k1, k2])
print(K.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 
 tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([2, 3, 3])
tensor([[1., 2.],
        [3., 4.]]) 
 tensor([[0., 1.],
        [2., 3.]])
torch.Size([2, 2, 2])


In [9]:
corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [10]:
X = torch.rand(3, 3, 3)
K = torch.rand(3, 2, 2)
zip(X, K)

In [11]:
print(X, K)

tensor([[[0.6211, 0.6390, 0.3107],
         [0.1240, 0.4980, 0.6314],
         [0.1084, 0.4268, 0.0809]],

        [[0.7977, 0.6423, 0.9722],
         [0.9570, 0.3614, 0.0707],
         [0.9442, 0.7366, 0.9719]],

        [[0.5981, 0.3794, 0.9532],
         [0.4325, 0.9573, 0.6565],
         [0.5572, 0.3857, 0.1771]]]) tensor([[[0.7102, 0.3305],
         [0.6978, 0.4978]],

        [[0.1133, 0.9595],
         [0.6459, 0.6039]],

        [[0.7627, 0.5535],
         [0.9434, 0.6433]]])


In [12]:
for x, k in zip(X, K):
  print(f" x = {x}")
  print(f" k = {k}")
  print('*' * 100)

 x = tensor([[0.6211, 0.6390, 0.3107],
        [0.1240, 0.4980, 0.6314],
        [0.1084, 0.4268, 0.0809]])
 k = tensor([[0.7102, 0.3305],
        [0.6978, 0.4978]])
****************************************************************************************************
 x = tensor([[0.7977, 0.6423, 0.9722],
        [0.9570, 0.3614, 0.0707],
        [0.9442, 0.7366, 0.9719]])
 k = tensor([[0.1133, 0.9595],
        [0.6459, 0.6039]])
****************************************************************************************************
 x = tensor([[0.5981, 0.3794, 0.9532],
        [0.4325, 0.9573, 0.6565],
        [0.5572, 0.3857, 0.1771]])
 k = tensor([[0.7627, 0.5535],
        [0.9434, 0.6433]])
****************************************************************************************************


In [13]:
sum(x for x, k in zip(X, K))

tensor([[2.0169, 1.6608, 2.2361],
        [1.5134, 1.8167, 1.3586],
        [1.6098, 1.5490, 1.2300]])

In [14]:
torch.sum(X, dim=0)

tensor([[2.0169, 1.6608, 2.2361],
        [1.5134, 1.8167, 1.3586],
        [1.6098, 1.5490, 1.2300]])

In [15]:
torch.stack??

In [16]:
def corr2d_multi_in_out(X, K):

  return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

In [17]:
K = torch.stack((K, K+1, K+2))
K.shape

torch.Size([3, 3, 2, 2])

In [18]:
X

tensor([[[0.6211, 0.6390, 0.3107],
         [0.1240, 0.4980, 0.6314],
         [0.1084, 0.4268, 0.0809]],

        [[0.7977, 0.6423, 0.9722],
         [0.9570, 0.3614, 0.0707],
         [0.9442, 0.7366, 0.9719]],

        [[0.5981, 0.3794, 0.9532],
         [0.4325, 0.9573, 0.6565],
         [0.5572, 0.3857, 0.1771]]])

In [19]:
corr2d_multi_in_out(X, K)

tensor([[[ 4.2197,  4.6424],
         [ 3.6840,  3.6431]],

        [[11.2275, 11.7146],
         [10.1729,  9.5974]],

        [[18.2354, 18.7867],
         [16.6619, 15.5517]]])

In [20]:
def corr2d_multi_in_out_1x1(X, K):
  c_i, h, w = X.shape
  c_o = K.shape[0]
  X = X.reshape(c_i, h * w)
  K = K.reshape(c_o, c_i)

  Y = torch.mm(K, X)
  return Y.reshape(c_o, h, w)

In [21]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))
print(f"X.shape = {X.shape}")
print(f"K.shape = {K.shape}")

X.shape = torch.Size([3, 3, 3])
K.shape = torch.Size([2, 3, 1, 1])


In [22]:
Y1 = corr2d_multi_in_out(X, K)
Y2 = corr2d_multi_in_out_1x1(X, K)

assert float(torch.abs(Y1-Y2).sum()) < 1e-6

In [23]:
print(f"Y1.shape = {Y1.shape}")
print(f"Y2.shape = {Y2.shape}")

Y1.shape = torch.Size([2, 3, 3])
Y2.shape = torch.Size([2, 3, 3])


## Ex 7.4:

### Q4:

In [24]:
Y1 == Y2

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])

# 7.5 : Pooling

In [25]:
import torch
from d2l import torch as d2l
from torch import nn

In [26]:
def pool2d(X, pool_size, mode='max'):
  p_h, p_w = pool_size
  Y = torch.zeros(X.shape[0]-p_h+1, X.shape[1]-p_w+1)
  
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      if mode == 'max':
        Y[i, j] = X[i:i+p_h, j:j+p_w].max()
      elif mode == 'avg':
        Y[i, j] = X[i:i+p_h, j:j+p_w].mean()

  return Y

In [27]:
X = torch.arange(0, 9, dtype=torch.float32).reshape(3, 3)
print(f"X = {X}")
print(f"pool2d(X) : {pool2d(X, (2, 2))}")

X = tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
pool2d(X) : tensor([[4., 5.],
        [7., 8.]])


In [28]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [29]:
X = torch.arange(0, 16, dtype=torch.float32).reshape(1, 1, 4, 4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [30]:
nn.MaxPool2d??

In [31]:
pool2d = nn.MaxPool2d(3)
pool2d

MaxPool2d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)

In [32]:
print(f"pool2d : {pool2d(X)}")
print(f"pool2d(X).shape : {pool2d(X).shape}")

pool2d : tensor([[[[10.]]]])
pool2d(X).shape : torch.Size([1, 1, 1, 1])


In [33]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d

MaxPool2d(kernel_size=(2, 3), stride=(2, 3), padding=(0, 1), dilation=1, ceil_mode=False)

In [34]:
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [35]:
a = nn.LazyConv2d(1, kernel_size=1, padding=1)
b = torch.arange(9, dtype=torch.float32).reshape(1, 1, 3, 3)
print(f"b = {b}")
print(f"a(b).shape = {a(b).shape}")

b = tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
a(b).shape = torch.Size([1, 1, 5, 5])


/usr/local/lib/python3.8/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [36]:
torch.cat??
# stacks along a given demension

In [38]:
torch.stack??
# stacks along a new dimension

In [39]:
# mutltiple input channels : 
X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
X = torch.cat([X, X+1], dim=1)
print(f"X = {X}")
print(f"X.shape = {X.shape}")

X = tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
X.shape = torch.Size([1, 2, 4, 4])


In [40]:
nn.MaxPool2d??

In [41]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

## Ex 7.5:

### Q1:

average pooling we need a kernel of ones multiplied with 1 / numel() 

- for pooling what all will be the inputs ?? 
- X will be rank 4 tensor : batch_size x channel x height x width

size of kernel : ?? rank 2 tensor (k_h x k_w)
 i need to define the kernel size : 
 also need stride : (s_h, s_w)

In [53]:
import math

In [54]:
math.floor(3.4)

3

In [116]:
for i in range(0, 2, 2):
  print(i)

0


In [115]:
a = torch.ones(3, 3) / 9.
b = torch.rand(1, 2, 4, 4)

In [117]:
corr2d_stride(b[0, 1], a, 2, 2)

K_h = 3, k_w = 3, f_h = 2, f_w = 2, s_h = 2, s_w = 2
 i = 0, j = 0


In [119]:
def corr2d(X, K):
  # X : rank 2 tensor
  # K : rank 2 tensor
  Y = torch.zeros(X.shape[0]-K.shape[0]+1, X.shape[1]-K.shape[1]+1)
  k_h, k_w = K.shape
  
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i, j] = (X[i:i+k_h, j:j+k_w] * K).sum()

  return Y

In [126]:
class Pool_Conv2d(nn.Module):

  def __init__(self, kernel_size):
    # kernel_size, stride both will be a tuple (h x w)
    # this layer won't have any bias
    # keeping stride to be (1, 1)
    super().__init__()
    self.k_h, self.k_w = kernel_size
    self.weight = nn.Parameter(torch.ones(kernel_size)) / float(self.k_h * self.k_w)

  def forward(self, X):
    # when we use pooling the rank of output is same as that of the input
    # X must be a rank 4 tensor
    # loop over batch_size and channel
    Y = torch.zeros(X.shape[0], X.shape[1], X.shape[2] - self.k_h + 1, X.shape[3] - self.k_w + 1)

    for i1 in range(Y.shape[0]):
      for i2 in range(Y.shape[1]):
        Y[i1, i2] = corr2d(X[i1, i2], self.weight)
        print(f"Y[i1, i2] for i1 = {i1} and i2 = {i2} : {Y[i1, i2]}")

    return Y

In [127]:
my_layer = Pool_Conv2d(kernel_size=(3, 3))
my_layer

Pool_Conv2d()

In [122]:
X = torch.arange(0, 16, dtype=torch.float32).reshape(1, 1, 4, 4)
print(X.shape)
X = torch.cat((X, X+1), 1)
print(X.shape)

torch.Size([1, 1, 4, 4])
torch.Size([1, 2, 4, 4])


In [124]:
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [128]:
my_layer(X)

Y[i1, i2] for i1 = 0 and i2 = 0 : tensor([[ 5.0000,  6.0000],
        [ 9.0000, 10.0000]], grad_fn=<SelectBackward0>)
Y[i1, i2] for i1 = 0 and i2 = 1 : tensor([[ 6.0000,  7.0000],
        [10.0000, 11.0000]], grad_fn=<SelectBackward0>)


tensor([[[[ 5.0000,  6.0000],
          [ 9.0000, 10.0000]],

         [[ 6.0000,  7.0000],
          [10.0000, 11.0000]]]], grad_fn=<CopySlices>)

In [87]:
a = torch.ones(2, 2, 4, 4)
a[1, 1].shape

torch.Size([4, 4])

In [51]:
c = (3, 4)
print(c[0])

3


In [44]:
b = torch.rand(3, 3)
b.size()

torch.Size([3, 3])

In [48]:
b_h, b_w = b.size()
print(f"b_h = {b_h}")
print(f"b_w = {b_w}")

b_h = 3
b_w = 3


In [49]:
type(b_h * b_w)

int

In [50]:
float(b_h * b_w)

9.0

In [46]:
a = nn.Parameter(torch.ones(b.size())) / b.numel()
a

tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]], grad_fn=<DivBackward0>)

In [66]:
a = torch.ones(4, 2, 4, 4)
print(a.shape)

torch.Size([4, 2, 4, 4])


In [68]:
a[1, 1].shape

torch.Size([4, 4])

max pooling can't be done through max pooling alone

### Q3:

In [133]:
a = torch.randn(1)
print(f"a = {a}")
print(torch.relu(a))

a = tensor([-0.3296])
tensor([0.])


In [134]:
def max_relu(a, b):
  # find maximum of a and b using only relu functions
  temp = torch.relu(a-b)
  ans = a if temp > 0 else b
  return ans

In [138]:
a = torch.randn(1)
b = torch.randn(1)

print(f"a = {a}, b = {b}")
print(max_relu(a, b))

a = tensor([-0.6161]), b = tensor([0.2817])
tensor([0.2817])


now to implement max pooling using convulations and relu : at each step of convulation we need to pass the input to max operation made using relu to get the maximum value of that step

In [ ]:
def corr2d_relu(X, K):
  # X : tensor of rank 2
  # K : tensor of rank 2
  # after applying convulation : pass 

In [ ]:
class MaxPool_relu(nn.Module):

  def __init__(self, kernel_size):
    # keeping stride = (1, 1)
    # weight : tensor of rank 2
    super().__init__()
    self.k_h, self.k_w = kernel_size
    self.weight = nn.Parameter(torch.ones(kernel_size))

  def forward(self, X):
    # X : tensor of rank 4
    f_h = X.shape[2] - self.k_h + 1
    f_w = X.shape[2] - self.k_w + 1
    Y = torch.zeros(X.shape[0], X.shape[1], f_h, f_w)

    for i1 in range(Y.shape[0]):
      for i2 in range(Y.shape[1]):
        Y[i1, i2] = corr2d_relu(X[i1, i2], self.weight)
    
    return Y


### Q5:

we are using the pooling layer after passing the input through the convulation layer so we already know where the features are present, where the values will be close to 1, now if use avg pooling layer, the overall value will be downsamples and its effect decreases. When we use a max pooling layer we are preserving the important information while downsampling


### Q6 : 
Minimum pooling layer can prove to be useful, because if we assume the rest of values in the input window is neglibile considered to the max value then we after applying max pooling, we would not loose any important information

But in the case when the values are close to the max value, in that case by just considering the maximum value from the respective window we loose out on important information

### Q7:

does not accuratley represent the magnitude of feature map

In [139]:
def softmax(x):
  # x is a tensor of rank 1
  x_exp = torch.exp(x)
  sum = torch.sum(x_exp)
  return x_exp / sum

In [140]:
a = torch.tensor([1, 0.01, 0.04, 0.005])
softmax(a)

tensor([0.4708, 0.1749, 0.1803, 0.1741])